version: '3.9'

x-ml_base: &ml_base
  # GPU support (requires Docker Engine and NVIDIA Container Toolkit)
  gpus: all
  shm_size: 8g
  environment:
    PYTHONUNBUFFERED: "1"
    MLFLOW_TRACKING_URI: "http://sacha-phd-mlflow:5000"
  depends_on:
    - sacha-phd-mlflow
  networks:
    - mlflow-net
  restart: unless-stopped
  tty: true

services:
  sacha-phd-mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: sacha-phd-mlflow
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
      --allowed-hosts "*"
    volumes:
      - /mlflow:/mlflow
    restart: unless-stopped
    networks:
      - mlflow-net

  sacha-phd-pytorch_parallelproj:
    <<: *ml_base
    container_name: sacha-phd-pytorch_parallelproj
    image: ghcr.io/sacha-phd-labs/pytorch_parallelproj:latest
    volumes:
      - /mlflow:/mlflow

networks:
  mlflow-net:
    name: mlflow-net
    driver: bridge
    attachable: true